name: hefekulturen
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.7
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - contourpy=1.2.0
  - decorator=5.1.1
  - freetype=2.12.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - jupyter_bokeh=4.0.1
  - jupyterlab_widgets=3.0.10
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=23.2
  - parso=0.8.3
  - pip=23.3.1
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - python=3.11.0
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pyyaml=6.0.1
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.3.3
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - anyio==4.1.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.13.1
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - bokeh==3.4.1
      - cachetools==5.3.3
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.0
      - cycler==0.12.1
      - debugpy==1.8.0
      - defusedxml==0.7.1
      - et-xmlfile==1.1.0
      - executing==2.0.1
      - fastjsonschema==2.19.0
      - filelock==3.14.0
      - fonttools==4.45.1
      - fqdn==1.5.1
      - h11==0.14.0
      - humanize==4.9.0
      - idna==3.6
      - imageio==2.33.0
      - ipyfilechooser==0.6.0
      - ipykernel==6.20.2
      - ipython==8.18.1
      - ipyvue==1.11.1
      - ipyvuetify==1.9.4
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.5.0
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.1
      - jupyter-server==2.11.1
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - linkify-it-py==2.0.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.6.3
      - mdit-py-plugins==0.4.1
      - mdurl==0.1.2
      - mistune==3.0.2
      - nbclient==0.9.0
      - nbconvert==7.11.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numpy==1.24.1
      - opencv-python==4.8.1.78
      - openpyxl==3.0.10
      - outlier-utils==0.0.5
      - overrides==7.4.0
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - panel==1.4.2
      - param==2.1.0
      - pexpect==4.9.0
      - pillow==9.4.0
      - platformdirs==4.0.0
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.41
      - psutil==5.9.6
      - pycparser==2.21
      - pygments==2.17.2
      - pymdown-extensions==10.8.1
      - pyparsing==3.1.1
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyviz-comms==3.0.2
      - pywavelets==1.5.0
      - pyzmq==25.1.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - reacton==1.8.3
      - referencing==0.31.0
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rich-click==1.8.2
      - rpds-py==0.13.1
      - scikit-image==0.21.0
      - scikit-learn==1.2.0
      - scipy==1.10.0
      - send2trash==1.8.2
      - sniffio==1.3.0
      - solara==1.32.2
      - solara-server==1.32.2
      - solara-ui==1.32.2
      - soupsieve==2.5
      - stack-data==0.6.3
      - starlette==0.37.2
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - tinycss2==1.2.1
      - tqdm==4.64.1
      - traitlets==5.14.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.11.0
      - uc-micro-py==1.0.3
      - uri-template==1.3.0
      - urllib3==2.1.0
      - uvicorn==0.29.0
      - watchdog==4.0.0
      - watchfiles==0.21.0
      - wcwidth==0.2.12
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - websockets==12.0
      - widgetsnbextension==4.0.9
      - xyzservices==2024.4.0
